<a href="https://colab.research.google.com/github/Comfy05/Football_analytics_portfolio/blob/main/statistics_football.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install mplsoccer
!pip install statsbombpy

Collecting mplsoccer
  Downloading mplsoccer-1.8.0-py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: matplotlib>=3.8 in /usr/local/lib/python3.12/dist-packages (from mplsoccer) (3.10.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from mplsoccer) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from mplsoccer) (2.2.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from mplsoccer) (11.3.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from mplsoccer) (2.32.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from mplsoccer) (1.16.3)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (from mplsoccer) (0.13.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->mplsoccer) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->mplsoccer) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->mplsoccer) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->mplsoccer) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->mplsoccer) (26.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->mplsoccer) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->mplsoccer) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->mplsoccer) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->mplsoccer) (2026.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->mplsoccer) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->mplsoccer) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->mplsoccer) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->mplsoccer) (2026.6.17)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.8->mplsoccer) (1.17.0)
Downloading mplsoccer-1.8.0-py3-none-any.whl (108 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.3/108.3 kB 4.1 MB/s eta 0:00:00
Installing collected packages: mplsoccer
Successfully installed mplsoccer-1.8.0
Collecting statsbombpy
  Downloading statsbombpy-1.22.0-py3-none-any.whl.metadata (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.8/63.8 kB 3.2 MB/s eta 0:00:00
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from statsbombpy) (2.2.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from statsbombpy) (2.32.4)
Collecting requests-cache (from statsbombpy)
  Downloading requests_cache-1.3.3-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: inflect in /usr/local/lib/python3.12/dist-packages (from statsbombpy) (7.5.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from statsbombpy) (1.5.3)
Requirement already satisfied: more_itertools>=8.5.0 in /usr/local/lib/python3.12/dist-packages (from inflect->statsbombpy) (10.8.0)
Requirement already satisfied: typeguard>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from inflect->statsbombpy) (4.5.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->statsbombpy) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->statsbombpy) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->statsbombpy) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->statsbombpy) (2026.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->statsbombpy) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->statsbombpy) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->statsbombpy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->statsbombpy) (2026.6.17)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache->statsbombpy) (26.1.0)
Collecting cattrs>=22.2 (from requests-cache->statsbombpy)
  Downloading cattrs-26.1.0-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests-cache->statsbombpy) (4.10.0)
Collecting url-normalize>=2.0 (from requests-cache->statsbombpy)
  Downloading url_normalize-3.0.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from cattrs>=22.2->requests-cache->statsbombpy) (4.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->statsbombpy) (1.17.0)
Downloading statsbombpy-1.22.0-py3-none-any.whl (18 kB)
Downloading requests_cache-1.3.3-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.8/70.8 kB 5.6 MB/s eta 0:00:00
Downloading cattrs-26.1.0-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 5.8 MB/s eta 0:00:00
Downloading url_normalize-3.0.0-py3-none-any.whl (16 kB)
Installing collected packages: url-normalize, cattrs, requests-cache, statsbombpy
Successfully installed cattrs-26.1.0 requests-cache-1.3.3 statsbombpy-1.22.0 url-normalize-3.0.0

In [33]:
from pandas.core.arrays import period
import pandas as pd
from statsbombpy import sb
from mplsoccer import Pitch, VerticalPitch
from matplotlib.pyplot import scatter
import matplotlib.pyplot as plt

competitions = sb.competitions()
event = sb.events(match_id=22912)

shots = event['type'] == 'Shot'
event_shots = event[shots][['player','location','team','minute', 'shot_outcome', 'shot_statsbomb_xg']]
event_shots['is_on_target'] = event_shots['shot_outcome'].isin(['Goal', 'Saved'])
shot_on_target = event_shots.groupby('team')['is_on_target'].sum().rename('on_target')
total_shots = event_shots.groupby('team').size().rename('all_shots')

print(shot_on_target)
print(total_shots)

team
Liverpool            3
Tottenham Hotspur    8
Name: on_target, dtype: int64
team
Liverpool            11
Tottenham Hotspur     8
dtype: int64
team
Liverpool            14
Tottenham Hotspur    16
Name: all_shots, dtype: int64

In [71]:
faul = event['type'] == 'Foul Committed'
event_offside = event[faul][['player','location','team','minute']]
fauls = event_offside.groupby('team').size()
fauls

team
Liverpool            10
Tottenham Hotspur     5
dtype: int64

In [103]:
offside = event['type'] == 'Offside'
event_offside = event[offside][['player','location','team','minute']]
offsides = event_offside.groupby('team').size().astype(int)
offsides

team
Tottenham Hotspur    1
dtype: int64

In [85]:
possession = event[['possession','possession_team']]
possession = possession.drop_duplicates('possession')
possession_value = possession.groupby('possession_team').size()
possession_value = possession_value/possession_value.sum() * 100
possession_value.round(2)

possession_team
Liverpool            49.42
Tottenham Hotspur    50.58
dtype: float64

In [97]:
from numpy import nan
passing = event['type'] == 'Pass'
event_pass = event[passing][['player','team','minute', 'pass_outcome']]
event_pass['good_pass'] = event_pass['pass_outcome'].isnull()
good_passes = event_pass.groupby('team')['good_pass'].sum()
total_passes = event_pass.groupby('team').size()

print(good_passes)
print(total_passes)

pass_accuracy = (good_passes/total_passes * 100).round(2)
print(pass_accuracy)

team
Liverpool            202
Tottenham Hotspur    447
Name: good_pass, dtype: int64
team
Liverpool            326
Tottenham Hotspur    564
dtype: int64
team
Liverpool            61.96
Tottenham Hotspur    79.26
dtype: float64

In [120]:
match_summary = pd.concat([total_shots, shot_on_target, possession_value, total_passes, pass_accuracy, fauls, offsides], axis=1).fillna(0).round(0)
match_summary.columns = ['all shots', 'shots on target', 'possession', 'passes', 'pass accuracy', 'fauls commited', 'offsides']
match_summary = match_summary.astype({'fauls commited': 'int', 'offsides':'int', 'possession': 'int', 'pass accuracy':'int'})
match_summary_transposed = match_summary.T
match_summary_transposed

                 Liverpool  Tottenham Hotspur
all shots               14                 16
shots on target          3                  8
possession              49                 51
passes                 326                564
pass accuracy           62                 79
fauls commited          10                  5
offsides                 0                  1

array([False,  True])